### ISSUE TITLE
Server error after compiling

### ISSUE THREAD

**Issue by Setup2134** [nokonoko/Uguu#105]
I cannot upload files after installing Uguu on my webserver
I thought it was a typo at first but issue persisted even after fixing the typo
W/o debug mode enabled it gives out a simple server error, I assume i may have messed up permissions in the database but i am not sure.

The error it spits out when Debug is enabled:
`FATAL Server error: Array ( [type] => 1 [message] => Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/uguu/dist/Classes/Connector.php:85 Stack trace: #0 /var/www/uguu/dist/Classes/Connector.php(85): PDO->__construct() #1 /var/www/uguu/dist/Classes/Upload.php(76): Pomf\Uguu\Classes\Connector->__construct() #2 /var/www/uguu/dist/public/upload.php(38): Pomf\Uguu\Classes\Upload->reFiles() #3 /var/www/uguu/dist/public/upload.php(57): handleFiles() #4 {main} thrown [file] => /var/www/uguu/dist/Classes/Connector.php [line] => 85 ) `

**Comment by Setup2134** [comment]
Turns out i forgot to change the path for the db file in config.json
