### ISSUE TITLE
Uploading of specific files causes PHP error

### ISSUE THREAD

**Issue by 776d** [nokonoko/Uguu#109]
When uploading specific files this PHP error may occur, excerpted from nginx error log but also shown in DEBUG mode or "Server error" not in DEBUG mode. Files uploaded are arbitrary. Offending files consistently cause this error. There are some files that upload successfully. Size nor type seem to matter. Hosting machine is an Ubuntu 24.04 LXD container.

```
2024/09/11 18:28:46 [error] 25663#25663: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /var/www/uguu/dist/Classes/Upload.php:84
Stack trace:
#0 /var/www/uguu/dist/Classes/Upload.php(84): hash_file()
#1 /var/www/uguu/dist/public/upload.php(38): Pomf\Uguu\Classes\Upload->reFiles()
#2 /var/www/uguu/dist/public/upload.php(57): handleFiles()
#3 {main}
  thrown in /var/www/uguu/dist/Classes/Upload.php on line 84" while reading response header from upstream, client: XXX.XXX.XXX.XXX, server: files.my.domain, request: "POST /upload.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.3-fpm.sock:", host: "files.my.domain", referrer: "https://files.my.domain/"
```

**Comment by nokonoko** [comment]
Something is wrong with your config, re-read the documentation and try again.
