### ISSUE TITLE
Unable to make 

### ISSUE THREAD

**Issue by GabenCrying** [nokonoko/Uguu#69]
I have completed the detailed installation instructions in the documentation, however, once I get to the end

```
/var/www/uguu$ make
mkdir -p /var/www/uguu/build /var/www/uguu/build/img
mkdir -p /var/www/uguu/build/classes /var/www/uguu/build/includes
"npm" install
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm notice created a lockfile as package-lock.json. You should commit this file.
added 47 packages from 68 contributors and audited 47 packages in 2.349s

1 package is looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
"node" node_modules/swig/bin/swig.js render -j dist.json templates/faq.swig > /var/www/uguu/build/faq.html
"node" node_modules/swig/bin/swig.js render -j dist.json templates/index.swig > /var/www/uguu/build/index.html
"node" node_modules/swig/bin/swig.js render -j dist.json templates/tools.swig > /var/www/uguu/build/tools.html
"node" node_modules/htmlmin/bin/htmlmin /var/www/uguu/build/index.html -o /var/www/uguu/build/index.html
"node" node_modules/htmlmin/bin/htmlmin /var/www/uguu/build/faq.html -o /var/www/uguu/build/faq.html
"node" node_modules/htmlmin/bin/htmlmin /var/www/uguu/build/tools.html -o /var/www/uguu/build/tools.html
"node" /var/www/uguu/node_modules/.bin/cleancss --skip-rebase --O1 specialComments:0 /var/www/uguu/static/css/uguu.css --output /var/www/uguu/build/uguu.min.css
echo "// @source https://github.com/nokonoko/uguu/tree/master/static/js" > /var/www/uguu/build/uguu.min.js
echo "// @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&dn=expat.txt Expat" >> /var/www/uguu/build/uguu.min.js
"node" /var/www/uguu/node_modules/.bin/uglifyjs  --screw-ie8 ./static/js/app.js >> /var/www/uguu/build/uguu.min.js
Parse error at ./static/js/app.js:257,38
  window.addEventListener("paste", e =>{
                                      ^
SyntaxError: Unexpected token: operator (>)
    at JS_Parse_Error.get (eval at <anonymous> (/var/www/uguu/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at /var/www/uguu/node_modules/uglify-js/bin/uglifyjs:384:40
    at time_it (/var/www/uguu/node_modules/uglify-js/bin/uglifyjs:620:15)
    at /var/www/uguu/node_modules/uglify-js/bin/uglifyjs:345:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
make: *** [Makefile:40: min-js] Error 1
```

I am unsure how I can fix this. Anyone know whats going on here? Appreciate any help

**Comment by nokonoko** [comment]
I'll check it out, give me a few minutes.

**Comment by GabenCrying** [comment]
> I'll check it out, give me a few minutes.

Thank you, I appreciate it

**Comment by nokonoko** [comment]
Sorry about that, I forgot to update a dependancy. If you clone the repo and try again it should work.

**Comment by nokonoko** [comment]
Confirmed to work now, at least for me. Just pushed the last changes.

**Comment by GabenCrying** [comment]
> Confirmed to work now, at least for me. Just pushed the last changes.

Groovy man it compiled like a charm, thank you very much for your work!!

**Comment by nokonoko** [comment]
Sweet! Thanks and no problem.
