### ISSUE TITLE
Error upon running make: "Could not find the include file"

### ISSUE THREAD

**Issue by tony-ze-yi** [nokonoko/Uguu#79]
I get an "Could not find the include file" error when trying to run `make` on uguu. I am running it in the root directory (/var/www/uguu). For example, I get this error:

```
Error: /var/www/uguu/src/templates/tools.ejs:1
 >> 1| <%- include('./src/templates/partials/header.ejs'); -%>
    2| <div class="container">
    3|     <div class="jumbotron">
    4|         <h1><%= siteName %> Tools</h1>

Could not find the include file "./src/templates/partials/header.ejs"
    at getIncludePath (/var/www/uguu/node_modules/ejs/lib/ejs.js:185:13)
    at includeFile (/var/www/uguu/node_modules/ejs/lib/ejs.js:311:19)
    at include (/var/www/uguu/node_modules/ejs/lib/ejs.js:701:16)
    at eval ("/var/www/uguu/src/templates/tools.ejs":10:17)
    at tools (/var/www/uguu/node_modules/ejs/lib/ejs.js:703:17)
    at exports.render (/var/www/uguu/node_modules/ejs/lib/ejs.js:425:37)
    at Immediate.run (/var/www/uguu/node_modules/ejs/bin/cli.js:200:20)
    at process.processImmediate (node:internal/timers:476:21) {
  path: '/var/www/uguu/src/templates/tools.ejs'
}

Node.js v18.15.0
make: *** [Makefile:29: ejs] Error 1
➜  uguu git:(master) ✗ ls -altrh
total 440K
-rwxrwxr-x   1 root root    8 Mar  9 16:52 .node_version
-rwxrwxr-x   1 root root   27 Mar  9 16:52 .mailmap
-rwxrwxr-x   1 root root    0 Mar  9 16:52 .gitmodules
-rwxrwxr-x   1 root root  146 Mar  9 16:52 .gitignore
-rwxrwxr-x   1 root root   25 Mar  9 16:52 .sonarcloud.properties
-rwxrwxr-x   1 root root 2.3K Mar  9 16:52 README.md
-rwxrwxr-x   1 root root 3.3K Mar  9 16:52 .php-cs-fixer.cache
-rwxrwxr-x   1 root root 4.9K Mar  9 16:52 Makefile
drwxrwxr-x   4 root root 4.0K Mar  9 16:52 docker
drwxrwxr-x   8 root root 4.0K Apr  7 20:05 ..
drwxrwxr-x   5 root root 4.0K Apr  7 20:21 src
-rwxrwxr-x   1 root root  703 Apr  7 20:21 package.json
drwxrwxr-x   8 root root 4.0K Apr  7 20:25 .git
drwxr-xr-x 339 root root  12K Apr  7 20:32 node_modules
drwxr-xr-x   8 root root 4.0K Apr  7 20:32 build
drwxrwxr-x   7 root root 4.0K Apr  7 20:32 .
-rwxrwxr-x   1 root root 367K Apr  7 20:32 package-lock.json
➜  uguu git:(master) ✗ stat /var/www/uguu/src/templates/partials/header.ejs
  File: /var/www/uguu/src/templates/partials/header.ejs
  Size: 474             Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 5414475     Links: 1
Access: (0775/-rwxrwxr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-04-07 20:20:20.043946658 -0400
Modify: 2023-03-09 16:52:20.391358530 -0500
Change: 2023-04-07 20:26:34.591835344 -0400
 Birth: 2023-03-09 16:52:20.391358530 -0500
```

I fixed this by adding the following code in every file that has this error:
```
<% var dir = process.cwd() %>
<%- include(dir + '/src/templates/partials/header.ejs'); -%>
```

Every `include()` is edited to include the `dir` variable. With this, it works fine. Not sure why that is. For debugging purposes here is my npm and nodejs version:

```
➜  uguu git:(master) ✗ npm --version
9.6.4
➜  uguu git:(master) ✗ node --version
v18.15.0
➜  uguu git:(master) ✗ rg "include\("
src/templates/faq.ejs
2:<%- include(dir + '/src/templates/partials/header.ejs'); -%>
65:<%- include(dir + '/src/templates/partials/footer.ejs'); -%>

src/templates/tools.ejs
2:<%- include(dir + '/src/templates/partials/header.ejs'); -%>
60:<%- include(dir + '/src/templates/partials/footer.ejs'); -%>

src/templates/index.ejs
2:<%- include(dir + '/src/templates/partials/header.ejs'); -%>
5:        <%- include(dir + '/src/templates/partials/lead.ejs'); -%>
6:        <%- include(dir + '/src/templates/partials/upload_form.ejs'); -%>
10:        <%- include(dir + '/src/templates/partials/malware_banner.ejs'); -%>
14:        <%- include(dir + '/src/templates/partials/donation_banner.ejs'); -%>
16:<%- include(dir + '/src/templates/partials/footer.ejs'); -%>

src/templates/partials/footer.ejs
2:<%- include(dir + '/src/templates/partials/nav.ejs'); -%>
```

**Comment by kkwpsi** [comment]
The same problem. Unfortunately, [tony-ze-yi](https://github.com/tony-ze-yi)'s way throws more errors.

**Comment by nokonoko** [comment]
What version of Node are u running?

**Comment by tony-ze-yi** [comment]
`v18.15.0`

**Comment by nokonoko** [comment]
Try 19.3 or above.

**Comment by nokonoko** [comment]
Also did u run "npm install" before "make"?

**Comment by tony-ze-yi** [comment]
Upgraded to node 19.9.0, still same issue once I revert the changes I made. And yes, I ran npm install before make.

**Comment by zkm2** [comment]
The paths are all wrong
quick and dirty fix:
`sed -i 's#./src/templates/#./#' ./src/templates/*.ejs`
`sed -i 's#./src/templates/partials/#./#' ./src/templates/partials/*.ejs`

**Comment by 7zx** [comment]
Thank you, @zkm2 . I had the same issue and the commands were very helpful to me. @nokonoko, could you please update the Uguu documentation when you have the time?

**Comment by nokonoko** [comment]
Totally missed that, my bad! I've merged the fix where the paths are fixed so downloading the latest release should function without running the sed commands.
