### ISSUE TITLE
npm install fails on ARM64 docker host

### ISSUE THREAD

**Issue by Tan-tan-san** [nokonoko/Uguu#81]
Trying to deploy on an ARM64 SBC so that might be part of the problem. When following the install instructions I run into this error when running the npm install. Just want to confirm if this is an AMD64 only if it supports ARM chips like the RK3588 on the orange pi 5?

```
user@opi:~/data/uguu$ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'minify@9.2.0',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'html-minifier-terser@7.2.0',
npm WARN EBADENGINE   required: { node: '^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'commander@10.0.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'node-downloader-helper@2.1.6',
npm WARN EBADENGINE   required: { node: '>=14.18' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     '/home/anona/data/uguu/node_modules',
npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/home/anona/data/uguu/node_modules/pngquant-bin'] {
npm WARN cleanup       errno: -39,
npm WARN cleanup       code: 'ENOTEMPTY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/home/anona/data/uguu/node_modules/pngquant-bin'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /home/anona/data/uguu/node_modules/pngquant-bin
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! compiling from source
npm ERR! Command failed: /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant --version
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 1: ELF: not found
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 7: G@Pu%@G8Pu%��L0Pu%pG(Pu%�%G Pu%P�LPu%GH�H��H��t��H���%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f���K5f��H��0�R���pyR��yR�҃H�� �R���pyR��yR赃H����R���PyR�0}R蘃H����R��@�R�K�R諹�H��(�S1��V�
npm ERR!
npm ERR! f.�f�H�au5H��t���O�H���u�H���:�f.�SA���H�ĀdH�%(H�D$x1�H��H���H�H��D���D$X�?����H����H�T$xdH3%(uH��[���e
�q5H��t�H��녿�D�5q5�V�0��I���I�Z5H�?Z5��I���<�BZ5H��H��H���VE1�A��5�p5����A��~oE�ҾtA]�A���1�E1�A�A��yD����tH������������u%@��tH���H�H��H��E��uE��tL��Mc�H�I��I��L�H�`p5H���1����)��������        ��I���� ��H���� I�����M�����I=�wK�����ǉ�t
npm ERR! �����uFLŁ��v���������o�����y5�����`��������Ǹ������L����H�H��I���A��
npm ERR! �E�����1�A��@�ǉ�!�E������A��<        ������D�΅���D����D�N��ہ������������u�@��t�A��A������C�A�����A��A!��@���I��������%�A���.���L��A���A�����1������@���g���A����A��A�������A��A��A!ڃ���>���A��A���E��~dA��A�BunE���fn5�dn5tdA��D����������������7��&��������H�HHH��H�¸AD�������A��t�1�E�������������r���1�E�����������A��A�������A��A��A!��@���A����!��\����1�I��^H��H���PTI����DH���DH���@g�]��ku��D]�fD��kuUH���kuH��H��H��H��?H�H��t�H��t]��ku��]�fD�=y`5uUH���~�����lOH��t: File name too long
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 1: �S: not found
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 1: G: not found
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 8: �T��5]Ð��@f.��@jOH��tU�: not found
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 9: Syntax error: ")" unexpected
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 1: Gu�$�=: not found
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 1: Gu: not found
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 1:Q�tdR�td: not found
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 1: Gu: not found
npm ERR! /home/anona/data/uguu/node_modules/pngquant-bin/vendor/pngquant: 2: @@h�@8@@@�9�9: not found
npm ERR!
npm ERR!
npm ERR! pngquant pre-build test failed
npm ERR! Error: pngquant failed to build, make sure that libpng-dev is installed
npm ERR!     at /home/anona/data/uguu/node_modules/bin-build/node_modules/execa/index.js:231:11
npm ERR!     at runMicrotasks (<anonymous>)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR!     at async Promise.all (index 0)
```

**Comment by nokonoko** [comment]
Hi!

From what I can see you're running Node v12, try updating it to v19 and re-downloading Uguu and compiling it again.

**Comment by GizmoTjaz** [comment]
I'm also having trouble with installing the dependencies on an ARM64 host.
```
$> npm i
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code 1
npm ERR! path /opt/Uguu/node_modules/pngquant-bin
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! compiling from source
npm ERR! Command failed: /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant --version
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 1: ELF: not found
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 7: G@Pu%@G8Pu%��L0Pu%pG(Pu%�%G Pu%P�LPu%GH�H��H��t��H���%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��%�K5f��H��0�R��
                                                                                                       �pyR��yR�҃H�� �R��
���                                                                                                                    �pyR��yR赃H����R���PyR�0}R蘃H����R��@�R�K�R諹�H��(�S1��V�
npm ERR!
npm ERR! f.�f�H�au5H��t���O�H���u�H���:�f.�SA���H�ĀdH�%(H�D$x1�H��H���H�H��D���D$X�?����H����H�T$xdH3%(uH��[���e
npm ERR! AWAVAUATUSH��
�q5H��t�H��녿�D�5q5�V�@0��I���I�Z5��I���<�H�H��H���VE1�A��5�p5����A��~oE�Ҿt�A���1�E1�A�A��yD����tH������������u%@��t������%�A��A��A�����
H���H�H��H��E��uE��tL��Mc�H�I��I��L�H�`p5H���1����)��������	��I����	��H����	I�����M�����I=�wK�����ǉ�t                                    ���E1�A��5^p5H��~��t
npm ERR! �����uFLŁ��v���������o�����y5�����`�������
                                                   �Ǹ������L����H�H��I���A��
npm ERR! �E�����1�A��@�ǉ�!�E������A�
                                    �<	������D�΅���D����D�N��ہ������������u�@��t�A��A������C�A�����A��A!��@���I��������%�A���.���L��A���A�����1������@���g���A����A��A�������A��A��A!ڃ���>���A��A���E��~dA��A�BunE���fn5�dn5tdA��D����������������7��&��������H�HHH��H�¸AD�������A��t�1�E�������������r���1�E�����������A��A�������A��A��A!��@���A����!��\����1�I��^H��H���PTI����DH���DH���@g�6��DU��kuH=�]��ku��D]�fD��kuUH���kuH��H��H��H��?H�H��t�H��t
                                               ]��ku��]�fD�=y`5uUH���~�����lOH��t: File name too long
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 1: �S: not found
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 8: �T��5]Ð��@f.��@jOH��tU�: not found
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 9: Syntax error: ")" unexpected
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 1: G: not found
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 1: Gu�$�=: not found
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 1: Gu: not found
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 1:Q�tdR�td: not found
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 1: Gu: not found
npm ERR! /opt/Uguu/node_modules/pngquant-bin/vendor/pngquant: 2: @@h�@8@@@�9�9: not found
npm ERR!
npm ERR!
npm ERR! pngquant pre-build test failed
npm ERR! Error: pngquant failed to build, make sure that libpng-dev is installed
npm ERR!     at /opt/Uguu/node_modules/bin-build/node_modules/execa/index.js:231:11
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async Promise.all (index 0)
```

I'm running Node 19, as you suggested above.
```
$> node -v
v19.9.0
```
